version: '3'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:80
  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - ./setup/.env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data